I = imread('C:\Users\Marjan\Documents\MATLAB\sio.jpg');
m=rgb2gray(I);
figure,imshow(I);title('orginal image');
x = edge(m,'canny');
figure,imshow(x);title('canny Filter');
w = edge(m,'sobel');
figure,imshow(w);title('sobel Filter');
y = edge(m,'prewitt');
figure,imshow(y);title('prewitt Filter');
z = edge(m,'roberts');
figure,imshow(z);title('roberts Filter');
